baseURL = "/"
languageCode = "en-uk"
title = "Arcapola Boat Co."

theme = "simple-hugo-theme"

paginate = 3
paginatePath = "page"

copyright = "(c) 2019 - Arcapola Boat Co. - All rights reserved."

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

[taxonomies]
	tag = "tags"
	category = "categories"

[menu]
	[[menu.main]]
		url = "/kb/"
		name = "knowledge base"
		weight = 1
	[[menu.main]]
		url = "/team/"
		name = "team"
		weight = 2

	[[menu.footer]]
		url = "/index.xml"
		name = "RSS"
		weight = 1
	[[menu.footer]]
		url = "mailto:peter@arcapola.com"
		name = "Contact"
		weight = 2

[params]
	datefmt = "2006-01-02"
