baseURL = "https://blog.arcapola.com"
languageCode = "en-uk"
title = "Arcapola Boat Co."

theme = "simple-hugo-theme"

paginate = 3
paginatePath = "page"

copyright = "(c) 2019 - Arcapola Boat Co. - All rights reserved."

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

[taxonomies]
	tag = "tags"
	category = "categories"

[menu]
	[[menu.main]]
		url = "/posts/"
		name = "blog"
		weight = 1
	[[menu.main]]
		url = "/about/"
		name = "about"
		weight = 2

	[[menu.footer]]
		url = "/posts/index.xml"
		name = "RSS"
		weight = 1
	[[menu.footer]]
		url = "mailto:peter@arcapola.com"
		name = "Contact"
		weight = 2

[permalinks]
	posts = "/posts/:year/:month/:title/"

[params]
	datefmt = "2006-01-02"
